const assistantView=document.createElement('main');
assistantView.id='assistant-view';assistantView.className='hidden';
assistantView.innerHTML=`<div class="topline"><div><h1 tabindex="-1">AI-помощник</h1><p class="muted">Задайте вопрос о закупках или разберите расчёт выбранного товара.</p></div><button id="chat-clear">Новый диалог</button></div>
<div class="panel"><div class="chat-controls"><label class="field">Помощник<select id="chat-provider" aria-label="Провайдер AI"></select></label><label class="field">Данные для ответа<select id="chat-product"><option value="">Общая сводка закупок</option></select></label><button id="chat-data">Открыть данные</button></div>
<div id="chat-connection" class="notice" role="status">Проверяем подключение помощника…</div>
<div id="chat-log" class="chat-log" role="log" aria-label="Диалог с AI" aria-live="polite"></div>
<div class="chat-hints"><button data-prompt="С чего начать проверку плана закупок?">С чего начать?</button><button data-prompt="Объясни расчёт выбранного товара и причины блокировки, если они есть.">Объяснить расчёт товара</button></div>
<form id="chat-form" class="chat-compose"><label for="chat-question">Ваш вопрос</label><textarea id="chat-question" maxlength="4000" required placeholder="Например: почему нужно заказать такое количество?"></textarea><p class="muted">При отправке вопроса текст диалога, сводка и данные выбранного товара передаются выбранному AI-сервису. Ответы не изменяют план закупок.</p><div class="actions"><button class="primary" id="chat-send" disabled>Отправить</button><span id="chat-progress" role="status"></span></div><div id="chat-error" class="notice error hidden" role="alert"></div></form></div>`;
document.querySelector('#workspace').before(assistantView);
let chatHistory=[],chatPending=false,chatProviders=[],chatGeneration=0,chatReportVersion=null,chatConfigurationRequest=0;
function showMode(mode){
  for(const [id,value] of [['welcome','home'],['workspace','plan'],['assistant-view','ai'],['operations-view','manual']])document.getElementById(id)?.classList.toggle('hidden',mode!==value);
  document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===(mode==='plan'?'manual':mode))));
  if(mode==='manual'){window.opsOpen();return;}
  const view=document.getElementById(mode==='ai'?'assistant-view':mode==='plan'?'workspace':'welcome');
  const heading=view.querySelector('h1');heading.setAttribute('tabindex','-1');heading.focus();
  if(mode==='ai'){syncChatProducts();loadChatConfiguration();}
}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>showMode(b.dataset.mode));
function addChatMessage(role,text){const item=document.createElement('div');item.className='chat-message '+role;const label=document.createElement('strong');label.textContent=role==='user'?'Вы':'Помощник';item.append(label,document.createTextNode(text));$('#chat-log').append(item);item.scrollIntoView({block:'nearest'});return item;}
function resetChat(message){chatGeneration++;chatHistory=[];$('#chat-log').replaceChildren();addChatMessage('assistant',message||'Здравствуйте! Помогу разобраться в плане закупок. Для вопроса об отдельном товаре выберите его над чатом.');$('#chat-error').classList.add('hidden');}
function syncChatProducts(){const select=$('#chat-product'),previous=select.value,version=report?((report.instance_id||'')+'|'+report.dataset+'|'+(report.report_revision??report.created_at)):null;select.innerHTML='<option value="">Общая сводка закупок</option>'+(report?.rows||[]).map(r=>`<option value="${esc(r.key)}">${esc(r.sku)} · ${esc(r.name)} · ${esc(r.supplier)}</option>`).join('');if([...select.options].some(o=>o.value===previous))select.value=previous;if(chatReportVersion!==version){const hadContext=chatReportVersion!==null||chatPending||chatHistory.length>0;chatReportVersion=version;if(hadContext)resetChat('Данные расчёта обновились. Начинаем новый диалог по текущему плану закупок.');}}
function updateChatAvailability(){const ready=chatProviders.find(p=>p.id===$('#chat-provider').value)?.ready,calculating=busy||jobSubmitting;$('#chat-send').disabled=chatPending||calculating||!ready;$('#chat-provider').disabled=chatPending;$('#chat-product').disabled=chatPending;$('#chat-clear').disabled=chatPending;$('#chat-question').disabled=chatPending;document.querySelectorAll('[data-prompt]').forEach(b=>b.disabled=chatPending);$('#chat-connection').textContent=calculating?'Дождитесь завершения расчёта: помощник ответит по обновлённым данным.':ready?'Подключение настроено. Доступ к модели проверяется при отправке вопроса.':'AI ещё не подключён. Попросите администратора настроить подключение. Работа вручную доступна.';}
async function loadChatConfiguration(){if(chatPending)return;const request=++chatConfigurationRequest;try{const data=await api('/api/assistant/config');if(request!==chatConfigurationRequest||chatPending)return;if(!Array.isArray(data.providers))throw Error('Некорректная конфигурация');chatProviders=data.providers;const previous=$('#chat-provider').value;$('#chat-provider').innerHTML=chatProviders.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}${p.ready?'':' — не подключён'}</option>`).join('');$('#chat-provider').value=chatProviders.some(p=>p.id===previous)?previous:chatProviders.find(p=>p.ready)?.id||chatProviders[0]?.id||'';updateChatAvailability();}catch(e){if(request!==chatConfigurationRequest||chatPending)return;chatProviders=[];updateChatAvailability();$('#chat-connection').textContent='Не удалось проверить подключение. Откройте AI-режим повторно.';}}
$('#chat-provider').onchange=()=>{resetChat();updateChatAvailability();};$('#chat-product').onchange=resetChat;
$('#chat-clear').onclick=resetChat;$('#chat-data').onclick=()=>{showMode('plan');tab('quality');};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#chat-question').value=b.dataset.prompt;$('#chat-question').focus();});
$('#chat-form').onsubmit=async e=>{e.preventDefault();if(chatPending||$('#chat-send').disabled)return;const question=$('#chat-question').value.trim();if(!question)return;chatPending=true;const generation=chatGeneration;updateChatAvailability();$('#chat-error').classList.add('hidden');$('#chat-progress').textContent='Помощник готовит ответ…';const bubble=addChatMessage('user',question);try{const result=await api('/api/chat',{provider:$('#chat-provider').value,product_key:$('#chat-product').value,message:question,history:chatHistory.slice(-12)},75000);if(generation!==chatGeneration){$('#chat-error').textContent='За время ответа данные изменились. Отправьте вопрос повторно по обновлённому плану.';$('#chat-error').classList.remove('hidden');return;}if(typeof result.answer!=='string'||!result.answer.trim())throw Error('AI не вернул текстовый ответ. Повторите запрос.');addChatMessage('assistant',result.answer);chatHistory.push({role:'user',content:question},{role:'assistant',content:result.answer});chatHistory=chatHistory.slice(-12);$('#chat-question').value='';}catch(err){bubble.remove();if(generation===chatGeneration){$('#chat-error').textContent=err.message;$('#chat-error').classList.remove('hidden');}}finally{chatPending=false;$('#chat-progress').textContent='';updateChatAvailability();}};
resetChat();
